---
- name: Install Flatpak applications
  hosts: localhost
  become: yes
  tasks:
    - name: Flatpak Install Check (Arch linux)
      pacman:
        name: flatpak
        state: present
      when: ansible_distribution in ["Archlinux", "CachyOS"]
    - name: Flatpak Install Check (Fedora)
      dnf:
        name: flatpak
        state: present
      when: ansible_distribution in ["Fedora", "CentOS", "RedHat"]
    - name: Flatpak Install Check (Ubuntu)
      apt:
        name: flatpak
        state: present
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  vars_files:
    - flatpaks.yml

  tasks:
    - name: Add Flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        # method: user

    - name: Install Flatpak applications
      flatpak:
        name: "{{ item }}"
        state: present
        # method: user
      loop: "{{ flatpak_packages }}"
