---
- name: Include flatpak variables
  include_vars: packages.yml

- name: Install Flatpak
  package:
    name: flatpak
    state: present

- name: Add Flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpak_packages }}"
